### ISSUE TITLE
About the recurrenting the paper

### ISSUE THREAD

**Issue by YihaoX** [driving-behavior/DBNet#12]
Hi dbnet team, thanks for the great paper and here comes some question.

1. It is said that NVIDIA net ([3,3] Convolution size of last two layers) is used in the paper but the network you provided in  _https://github.com/driving-behavior/DBNet/blob/master/models/nvidia_io.py_ is not the same ([5,5] Convolution size of last two layers). Could you tell me the reason for that?

2. May I confirm that did you use all the raw datas in _http://www.dbehavior.net/download.aspx_ for the network training in the paper? 

Cheers!

**Comment by wangjksjtu** [comment]
Hi, thanks for the interest in our work!
1)  I checked the code in `nvidia_io.py`. It is indeed not consistent with nvidia network. I guess it happens because the re-organization of the code. I will adjust the network architecture if time permits, or any pull-requests are welcomed!
2) The data trained in the paper only contains partial data. We continued collecting data after the submission. Now the data is 10 times larger than KITTI. To get the baseline performance, please refer to the leaderboard in the readme file. Thanks :)

**Comment by YihaoX** [comment]
> Hi, thanks for the interest in our work!
> 
> 1. I checked the code in `nvidia_io.py`. It is indeed not consistent with nvidia network. I guess it happens because the re-organization of the code. I will adjust the network architecture if time permits, or any pull-requests are welcomed!
> 2. The data trained in the paper only contains partial data. We continued collecting data after the submission. Now the data is 10 times larger than KITTI. To get the baseline performance, please refer to the leaderboard in the readme file. Thanks :)

Thank you :D!
