### ISSUE TITLE
Request driver behavior data download with high sampling rate

### ISSUE THREAD

**Issue by JinghangLi** [driving-behavior/DBNet#15]
Hi dbnet team, thank you for your patience with my questions earlier. But now I have a new question here.

I downloaded the data set of the original video, but there's no data about the driver's behavior.
Can you open the download of driver behavior data with high sampling rate.

Thank you very much.

**Comment by wangjksjtu** [comment]
Hi Jinghang, 
Unfortunately, we could not provide the corresponding driving behavior data with higher sampling rate due to the limit of sensors. If you indeed need them, you can consider interpolation or other tricks to obtain missing data. Also the speed/angle won't change too much within one second.

**Comment by JinghangLi** [comment]
Get it.
thanks a lot for your help.
